name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1.20.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
